### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by mrGRINCH** [CPTProgrammer/ChatPlus#2]
Could you add an option to set a hotkey for linking an item in chat please?

**Comment by CPTProgrammer** [comment]
It's a **server-side** mod. It cannot detect the client's hotkeys.

You can try other client-side mods, such as [commandbinds (Link to Modrinth)](https://modrinth.com/mod/commandbinds)

**Comment by mrGRINCH** [comment]
How is this one able to do it?

https://modrinth.com/mod/show-me-what-you-got

Thank you for the additional mod suggestion though.

**Comment by CPTProgrammer** [comment]
Here's an excerpt from the mod's description:

> The mod _should_ be installed on the client _and_ the server in order to function properly.
> 
> Clients without the mod can still see items shared by others with the mod in chat, but can't share items themselves and also won't see the shared item's texture in the tooltip. If you use this mod on your client and try to share an item on a server without the mod installed, you will just send text with the item name.

This mod contains both server-side and client-side, where the client part completes the function of hotkeys. ChatPlus has only server-side mod.

But if you have other ideas, you are more than welcome to continue to comment!

**Comment by mrGRINCH** [comment]
Ah, my bad. I forgot it had a client side requirement to it also.
