### ISSUE TITLE
Dynmap online map chat not working with ChatPlus

### ISSUE THREAD

**Issue by HyperPaint** [CPTProgrammer/ChatPlus#5]
Hi, i found some incompatibility. When ChatPlus enabled on my fabric server, chat messages not sends to Dynmap (browser), but messages from Dynmap (browser) to game works good.

versions:
minecraft fabric 1.20.4
chat-plus 0.20.2-mc1.20.4
dynmap 3.7-SNAPSHOT

In logs there is no errors, warn or info.

Can you check, where problem can be? This is definitely related to this mod

**Comment by CPTProgrammer** [comment]
Thank you for raising this issue!
I'll try to address it as soon as possible

**Comment by CPTProgrammer** [comment]
The issue has been addressed. 
A new version was updated and released.

**Comment by HyperPaint** [comment]
Thank you!
